# Generated by Django 5.2.1 on 2025-07-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='Sin descripcion')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion', to='auth.group')),
            ],
        ),
    ]
