# Generated by Django 5.2.1 on 2025-07-09 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(default='No existe una descripcion')),
                ('bg_color', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('icono', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_content', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'descripcion_content_type',
            },
        ),
        migrations.CreateModel(
            name='DescripcionPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='No existe una descripcion')),
                ('bg_color', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('icono', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('permiso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_permiso', to='auth.permission')),
            ],
            options={
                'db_table': 'descripcion_permission',
            },
        ),
    ]
